In [8]:

x = np.ones([3,2], float)
y = np.zeros([3,2], float)
x, y

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [9]:
np.full((2, 5), 6, dtype=np.uint)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

In [10]:
np.ones([2, 5], dtype=np.uint) * 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

In [2]:
history

%history
history


In [3]:
np.zeros([2,5],dtype=np.unit)

NameError: name 'np' is not defined