In [44]:
from numpy import random
x = random.randint(10)
print(x)

1


In [54]:
from numpy import random as rd
x=rd.randint(100, size=(5)) # 1-D array
x

array([15, 32, 70, 84, 94])

In [37]:
from numpy import random
x = random.rand(5)
print(x)

[0.15815442 0.39694276 0.51183012 0.25099505 0.59417306]


In [38]:
from numpy import random
x = random.rand(3,5)
print(x)

[[0.14837298 0.53911391 0.51907709 0.35972823 0.90613968]
 [0.09892084 0.61147529 0.62197972 0.78755742 0.03227873]
 [0.35443351 0.94141487 0.94865445 0.08263825 0.65186606]]


In [43]:
from numpy import random
x = random.choice([1, 3, 5, 7, 9])
print(x)

7


In [53]:
from numpy import random
x = random.choice([1, 3, 5, 7, 9], size=(2,2))
print(x)

[[1 9]
 [1 9]]
