In [3]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.2, 0.3, 0.5, 0.0], size=(100))
print(x)

[5 5 7 3 3 5 7 5 7 3 5 7 7 7 5 7 5 7 7 5 7 5 3 7 5 5 7 7 3 7 7 5 7 5 7 7 3
 5 7 3 7 7 7 7 7 7 7 7 3 7 7 7 5 7 3 7 7 7 3 7 3 5 3 5 7 5 3 5 7 5 3 7 5 3
 7 7 5 7 3 3 7 3 5 3 7 7 3 7 7 3 7 5 7 7 5 7 5 3 7 7]


In [3]:
from numpy import random as rd
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(rd.permutation(arr))

[3 1 2 5 4]


In [6]:
from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[-0.64843475  1.26366401 -0.54808021]
 [ 2.67907586 -0.38080276  1.0860594 ]]


In [11]:
from numpy import random

x = random.binomial(n=10, p=0.5, size=10)

print(x)


[3 6 3 2 3 8 5 3 5 6]
